# Main config

# Basic info
site_name: BeBetter
site_description: My Network
site_author: Viktor Simov
repo_name: viktor-simov/readthedocs
repo_url: https://github.com/viktor-simov/readthedocs

# Extensions to MD
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


# Social network links
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viktor-simov
    - icon: fontawesome/brands/vk
      link: https://vk.com/1111111111
    - icon: fontawesome/brands/telegram
      link: https://t.me/11111111

# MKDocs theme params
theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: yellow
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
  font:
    code: "Fira Code"
    text: "Exo 2"
  logo: img/icon.png
  favicon: img/icon.png

#extra_css:
#  - stylesheets/extra.css

# Used plugins
plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - awesome-pages:
      collapse_single_pages: true
      strict: false

# Copyright
copyright: "Viktor Simov &copy; 2025"